# 1.数据类型

1.python数据类型对应的pytorch数据类型

Int对应IntTensor of size()

Int array对应IntTensor of size[,,,]

string在pytorch中没有直接支持，需要用one-hot编码，或者Embedding(用数字表示语言）

torch.FloatTensor(cpu运算类型)  torch.cuda.FloatTensor（gpu运算类型） 

torch.DoubleTensor

torch.ByteTensor

In [56]:
import torch
import numpy as np
a = torch.randn(2,3)#torch.randn随机创建正态分布的数组
print(a)
print(type(a))
isinstance(a,torch.FloatTensor)

tensor([[-0.8061,  0.5123, -0.8278],
        [ 0.3666, -0.6980, -1.0683]])
<class 'torch.Tensor'>


True

In [57]:
a = a.cuda()
isinstance(a,torch.cuda.FloatTensor)

True

# 1.1标量表示

In [58]:
b = torch.tensor(1.3)#pytorch中的标量表示方法

In [59]:
b.shape

torch.Size([])

In [60]:
len(b.shape)

0

In [61]:
b.size()

torch.Size([])

# 1.2张量

In [62]:
torch.tensor([1.1])#只有一个元素的向量
torch.tensor([1,2])#有两个元素的向量
torch.FloatTensor(2)#定义一个长度为2的向量，元素类型为float,值正态随机
data = np.ones(2)
data = torch.from_numpy(data)#将numpy中的数组转换为tensor类型
data.dim()

1

In [63]:
b = torch.randn(2,3)

In [64]:
b.dim()

2

In [65]:
b.size()

torch.Size([2, 3])

In [66]:
b.shape

torch.Size([2, 3])

In [67]:
b.size(0)

2

In [68]:
b.size(1)

3

In [69]:
b.numel()#占用的内存

6

# 1.3数据的创建

In [70]:
a = np.array([1,2])

In [71]:
torch.from_numpy(a)

tensor([1, 2], dtype=torch.int32)

In [72]:
a = np.ones([2,3])

In [73]:
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [74]:
torch.tensor([1,2])#小写的tensor,接受现有的数据，大写的是接受shape或数据
torch.FloatTensor(3,5)
torch.FloatTensor([1,5])

tensor([1., 5.])

In [75]:
torch.FloatTensor(3,1,28,28)#数据未初始化，是随机的，用之前要初始化

tensor([[[[6.4803e-40, 4.9138e-39, 1.2518e-40,  ..., 1.3313e-40,
           1.3313e-40, 9.9801e-39],
          [9.9542e-39, 9.6533e-39, 9.6546e-39,  ..., 2.6018e-39,
           2.6045e-39, 2.6064e-39],
          [2.6083e-39, 2.6101e-39, 2.6117e-39,  ..., 1.3614e-40,
           1.3621e-40, 1.3623e-40],
          ...,
          [1.2332e+01, 1.2328e+01, 1.0314e-08,  ..., 4.4721e+21,
           5.1607e+10, 1.2078e+01],
          [7.7582e-10, 4.1676e-17, 1.2332e+01,  ..., 7.7140e+31,
           2.4776e+32, 2.5148e+32],
          [3.9495e+30, 3.6319e+00, 3.8189e+00,  ..., 3.0346e+00,
           1.3781e+19, 6.8398e+25]]],


        [[[3.8186e+00, 1.0903e+27, 3.5491e+21,  ..., 7.3972e+31,
           4.7429e+30, 3.0064e+00],
          [1.4513e+10, 5.3314e+01, 2.7495e+26,  ..., 1.3281e+13,
           2.9965e+32, 1.7700e+25],
          [7.5592e+28, 3.6311e+00, 7.7089e+31,  ..., 7.7089e+31,
           3.0039e+00, 1.5232e+31],
          ...,
          [2.1734e+05, 1.8461e+25, 1.6883e+25,  ..., 3.00

In [76]:
#随机初始化
a = torch.rand(3,3)#元素在0-1间均匀分布
b = torch.randn(3,3)#正态分布
torch.rand_like(a)#接受一个Tensor,以它的形状创建一个随机的Tensor
torch.randint(1,10,[3,3])#创建3*3的元素在1-10，左闭右开

tensor([[7, 5, 8],
        [3, 5, 9],
        [5, 5, 7]])

In [77]:
torch.full([2,3],7.0)#元素全部设定为7

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [78]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [79]:
torch.linspace(0,10,steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [80]:
torch.logspace(0,-1,steps=10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [81]:
torch.ones(3,3)
torch.zeros(3,3)
torch.eye(3,3)#对角线全1，其余为0
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [82]:
a = torch.rand(2,3)
b = torch.rand(2,3)
idx = torch.randperm(2)#随机打乱顺序
print(a)
print(b)

tensor([[0.7276, 0.8848, 0.7889],
        [0.0889, 0.0939, 0.0755]])
tensor([[0.5189, 0.5739, 0.9918],
        [0.3369, 0.3465, 0.7563]])


In [83]:
print(a[idx])

tensor([[0.0889, 0.0939, 0.0755],
        [0.7276, 0.8848, 0.7889]])


In [84]:
print(b[idx])

tensor([[0.3369, 0.3465, 0.7563],
        [0.5189, 0.5739, 0.9918]])
